config/routes.rb
Rails.application.routes.draw do
  get "web/home"
  get "web/projects"
  get "web/contact"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "web#home"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/web_controller.rb
class WebController < ApplicationController
  def home
  end

  def projects
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/web_helper.rb
module WebHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Portafolio" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-navbar" data-bs-theme="dark">
      <div class="container-fluid">
        <%= image_tag 'rocket1.png', class:"rocket rounded-start mx-3" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
              <%= link_to 'Inicio', web_home_path, class:'nav-link active', 'aria-current': 'page' %>
              <%= link_to 'Proyectos', web_projects_path, class:'nav-link active', 'aria-current': 'page' %>
              <%= link_to 'Contacto', web_contact_path, class:'nav-link active', 'aria-current': 'page' %>
          </ul>
        </div>
      </div>
    </nav>



    <div class="container">
      <%= yield %>
    </div>






    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
 
  </body>
</html>

app/views/web/contact.html.erb
<h1 class="text-center py-4">Contacto</h1>


<div class="card mb-3 mx-auto w-25 >
  <div class="col-md-12">
    <div class="card-body">
       <h5 class="card-title">Rodolfo Cantillana</h5>
       <p class="card-text">rodolfo.cantillana@gmail.com</p>
       <p class="card-text">+56 9 55398707<small class="text-body-secondary"></small></p>
    </div>
  </div>
</div>

app/views/web/home.html.erb
<h1 class="my-5 text-center">Portafolio</h1>
<div class="card mb-3 mx-auto w-25 >
  <div class="row g-0">
    <div class="col-md-12">
      <%= image_tag 'Rod_aro.jpg', class:"rod  img_fluid rounded-start" %>
      
    </div>
    <div class="col-md-12">
      <div class="card-body">
        <h5 class="card-title">Rodolfo Cantillana</h5>
        <p class="card-text">Iniciando estudios en programacion Web. Actualmente cursando curso de Desarrollo de Aplicaciones Ruby On Rails</p>
        <p class="card-text">Desarrollador web en proceso de formación<small class="text-body-secondary"></small></p>
      </div>
    </div>
  </div>
</div>

app/views/web/projects.html.erb
<div class="row  my-5">
    <div class="card col px-0 mx-3" >
    <%= image_tag 'cuppon.JPG', class:"img_fluid rounded-start rounded-end" %>
    <div class="card-body">
        <h5 class="card-title">TIENDAS CUPPON</h5>
        <p class="card-text">Tienda digital que ofrece diversos productos con ofertas exclusivas. podras encontrar ropa, perfumes, cenas, viajes y estadias con ofertas de ultima hora.</p>
        <a href="#" class="btn boton">Vamos!</a>
    </div>
    </div>
    <div class="card px-0 col mx-3">
    <%= image_tag 'ricomida.JPG', class:"img_fluid rounded-start rounded-end" %>
    <div class="card-body">
        <h5 class="card-title">RICOMIDA Recetas y Cocina</h5>
        <p class="card-text">Compartimos con nuestra comunidad ricas y exquisitas recetas Gourmet para deleitarse junto a los que mas quieres</p>
        <a href="#" class="btn boton">Vamos!</a>
    </div>
    </div>
    <div class="card col px-0 mx-3" >
    <%= image_tag 'viajeschile.JPG', class:"img_fluid rounded-start rounded-end" %>
    <div class="card-body">
        <h5 class="card-title">Viajes Chile</h5>
        <p class="card-text">Servicios turisticos Viajes Chile, ofrece rutas y paquetes turisticos a Torres del Paine, Isla de Pascua, San Pedro de Atacama y otros.</p>
        <a href="#" class="btn boton">Vamos!</a>
    </div>
    </div>

</div>